### PR TITLE
Fix emsdk setup broken probably due to Python 3 urllib changes.

### PR DESCRIPTION
**Pull request by fungos**

### CODE REVIEW

**Comment by fungos** [comment]
Wasn't being able to setup emscripten via fips, it seems that the urllib api changed to python 3, but not sure as I do not know too much there. Also, not really sure you will want this one as it may break compatibility with python 2. I know there are some python tricks that we can do, I'm just not really into python to try it. :)

**Comment by fungos** [comment]
Well, I'm sure you'll not want this. The right fix should be put a message when trying to setup emscripten and abort if using python 3. :)

**Comment by floooh** [comment]
Hi @fungos, I'm currently in China, quite busy, and github is extremely slow so experimenting with emscripten-setup is not a good idea from here :) I'll have a look when I'm back in Germany, early next week!

**Comment by floooh** [comment]
PS: I'll open the pull request again as a reminder for me, even if we don't go with your commit.

**Comment by kkimdev** [comment]
I think we should change `#!/usr/bin/env python` to `#!/usr/bin/env python2` in `fips` script file.

**Comment by floooh** [comment]
I don't want to hardwire fips to python2 or python3 using the shebang, since ideally it should work with whatever python version is installed by default.

**Comment by kkimdev** [comment]
I see, I didn't know that was a goal :).

Though, in general, I think omitting the version should be discouraged since major version bump will include breaking changes that's not known ahead anyways, 3, 4, 5,...

**Pull request closed without merging**
