### PR TITLE
fips self-update

### PR DESCRIPTION
**Pull request by code-disaster**
Another small QoL change: `fips update fips` runs an update on the `fips` folder itself.

So, it's just a shortcut for:

~~~
cd ../fips
git pull
cd ../{proj}
~~~

I also allowed myself to bring the descriptions for `fips help` into line. Those slackers!

### CODE REVIEW

**Comment by floooh** [comment]
Very cool, thanks :)

Another thing I've been thinking about, but where I'm not sure if it's actually a good idea is that a normal "fips update" should also update the current project as well, not sure if there are situations where this would interfere with any "work in progress stuff"...

**Comment by floooh** [comment]
...hm it's not working here (it just does nothing) :) I'll have a look.

**Comment by floooh** [comment]
Ok, I had to do two minor changes:

https://github.com/floooh/fips/commit/3baadc9736e8ff1bcc6ff066fa7a98911ff39ca5

It's actually not easy to test that, since working on the fips directory means it always has local changed ;)

**Comment by code-disaster** [comment]
Ah dang it, damn last-minute-edits-to-test-stuff! Thanks for fixing.

**Comment by code-disaster** [comment]
> Another thing I've been thinking about, but where I'm not sure if it's actually a good idea is that a normal "fips update" should also update the current project as well, not sure if there are situations where this would interfere with any "work in progress stuff"...

Hm, I think this may be fine as long as it's doing fast-forward pulls/merges only. I wouldn't want it to auto-merge local with remote changes.

**Pull request merged**
