### PR TITLE
CMAKE: ios toolchain can't find gcc or g++ for me without the full path.

### PR DESCRIPTION
**Pull request by mgerhardy**

### CODE REVIEW

**Comment by floooh** [comment]
I don't understand this pull request :)

Do you want to build with make or ninja? 

When using the ios-xcode-debug build config and building from the command line, the clang executable from the iOS SDK is choosen, overriding this with the globally installed gcc would probably be wrong.

**Comment by mgerhardy** [comment]
I am building with xcodebuild. But it fails for me if this isn't a full path.

--
Martin Gerhardy
http://www.caveproductions.org

**Comment by floooh** [comment]
Strange, I'd like to find out why it works for me but not for you... can you paste a log of the build messages and what error occurs? For me it looks like this (see below), as you can see it directly calls the clang inside the iOS SDK (after './fips set config ios-xcode-debug', './fips gen', and './fips build').

Also: what versions of OSX and Xcode do you have installed, and did you install the Xcode command line tools?

```
CompileC /Users/floh/projects/fips-build/oryol/ios-xcode-debug/fips-imgui_imgui/oryol.build/Debug-iphoneos/imgui.build/Objects-normal/armv7/imgui.o /Users/floh/projects/fips-imgui/imgui/imgui.cpp normal armv7 c++ com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/floh/projects/oryol
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -arch armv7 -fmessage-length=138 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -std=c++11 -stdlib=libc++ -Wno-trigraphs -fno-exceptions -fno-rtti -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-shorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -DCMAKE_INTDIR=\"Debug-iphoneos\" -DORYOL_SYNTH_NUM_VOICES=2 -DORYOL_SYNTH_NUM_TRACKS_PER_VOICE=2 -DORYOL_POSIX=1 -DORYOL_OSX=1 -DORYOL_IOS=1 -DORYOL_OPENGL=1 -DORYOL_OPENGLES2=1 -DORYOL_OPENAL=1 -DORYOL_SAMPLE_URL=\"http://floooh.github.com/oryol/\" -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -miphoneos-version-min=9.2 -g -Wno-sign-conversion -fembed-bitcode-marker -I/Users/floh/projects/fips-build/oryol/ios-xcode-debug/fips-imgui_imgui/Debug-iphoneos/include -I/Users/floh/projects/oryol/code/Modules/TBUI/tb -I/Users/floh/projects/fips-libcurl -I/Users/floh/projects/fips-imgui/imgui -I/Users/floh/projects/fips-build/oryol/ios-xcode-debug/fips-imgui_imgui/oryol.build/Debug-iphoneos/imgui.build/DerivedSources/armv7 -I/Users/floh/projects/fips-build/oryol/ios-xcode-debug/fips-imgui_imgui/oryol.build/Debug-iphoneos/imgui.build/DerivedSources -Wmost -Wno-four-char-constants -Wno-unknown-pragmas -F/Users/floh/projects/fips-build/oryol/ios-xcode-debug/fips-imgui_imgui/Debug-iphoneos -fstrict-aliasing -Wno-multichar -Wall -Wextra -Wno-unused-parameter -Wno-unknown-pragmas -Wno-ignored-qualifiers -Wno-long-long -Wno-overloaded-virtual -Wno-unused-volatile-lvalue -Wno-deprecated-writable-strings -D_DEBUG_ -D_DEBUG -DFIPS_DEBUG=1 -Wno-unused-but-set-variable -Wno-type-limits -Wno-missing-field-initializers -MMD -MT dependencies -MF /Users/floh/projects/fips-build/oryol/ios-xcode-debug/fips-imgui_imgui/oryol.build/Debug-iphoneos/imgui.build/Objects-normal/armv7/imgui.d --serialize-diagnostics /Users/floh/projects/fips-build/oryol/ios-xcode-debug/fips-imgui_imgui/oryol.build/Debug-iphoneos/imgui.build/Objects-normal/armv7/imgui.dia -c /Users/floh/projects/fips-imgui/imgui/imgui.cpp -o /Users/floh/projects/fips-build/oryol/ios-xcode-debug/fips-imgui_imgui/oryol.build/Debug-iphoneos/imgui.build/Objects-normal/armv7/imgui.o
...
```

**Comment by floooh** [comment]
I have committed those 2 things in master (the changes I wrote about above, and the 2 lines from the other pull request), could you check whether it works for you? For me it didn't make any difference either way (at least with Oryol), I have cmake 3.4.3, Xcode 7.3 beta, iOS 9.3, OSX 10.11.4 beta.

**Comment by floooh** [comment]
@mgerhardy, when you got a minute to test, can you let me know if the current state works for you so I can close the 2 PRs? Thanks :)

**Comment by mgerhardy** [comment]
works for me now

**Pull request closed without merging**
