### PR TITLE
CMAKE: workaround code signing stuff

### PR DESCRIPTION
**Pull request by mgerhardy**
https://cmake.org/Bug/view.php?id=15329

this is just meant to be a reference if you ever stumble upon code signing for really putting something into the store and are not able to detect a single header or function anymore.

Not sure if you really want CMAKE_MACOSX_BUNDLE - but it must be in the toolchain file.

### CODE REVIEW

**Comment by floooh** [comment]
What happens when you omit these, does the build fail? The iOS build config already builds proper app bundles with a debug signature when building from the command line. I haven't implemented a way yet to deploy them to the device from the command line.

When building the ios-xcode-debug config (or -release) config from the command line (via 'fips build'), xcodebuild will be called, which should behave exactly the same as running the build from within Xcode.

**Comment by floooh** [comment]
PS: PS: cmake.org currently doesn't work for me :/ I'll try to have a look in the evening. I haven't tried yet to sign iOS apps without debug executable. How do you do this with cmake? Do you need to call another command line tool, or does xcodebuild take care of this?

**Comment by mgerhardy** [comment]
works for me now

**Comment by mgerhardy** [comment]
can be controlled by xcodebuild parameter, too

**Pull request closed without merging**
