### PR TITLE
Adding python3 compatibility

### PR DESCRIPTION
**Pull request by anthraxx**
- this includes the PyYAML python3 library (upstream separated them as they failed to provide it in the same source *facepalm*)
- the magic switch is done in yaml/__init__.py by checking py version

- Tested on Arch Linux and Debian using python3 and python2 on 4 computers to check for regression, seems to work fine

### CODE REVIEW

**Comment by floooh** [comment]
Cool stuff! I'll try to review, test and merge this tomorrow (Saturday). Thanks a lot :D

**Comment by anthraxx** [comment]
current status:
python2 still as is but python3 has a small issue and compiles everything all the time.
Current investigation:
there seem to be differences between python2 and 3 related to sorting of dictionaries, the yaml implementation is not always ordered and therefor the .tmp file check detects that the generated fips-imports file is different and removes the build dirs.
I found a matching PyYAML bug ticket (http://pyyaml.org/ticket/29) but it looks like we have to solve a stable ordering ourselves. the main problematic part seems to be the returned imports that are later used to iterate over them.
I guess it would make sense for fips to always load the yaml's in a stable order (and also possibly dump the settings yaml ordered).

**Comment by floooh** [comment]
Good catch. I think/hope the order of imports if only important in that tmp file comparison (https://github.com/floooh/fips/blob/master/mod/dep.py#L332), this check is a bit hacky anyway. I wonder if it's better to fix this check instead of adding code to to the pyyaml lib? We could re-sort the imports into a specific order before writing the imports file.

This only works if the order of imports in the fips.yml files doesn't matter. But I think they shouldn't (?)

**Comment by anthraxx** [comment]
Yeah thats not a bad idea. Actually I also had that idea and sorting the imports seemed to do the trick but I was unsure about possible implications and If the order is important. I do some more tests and can adjust the commit

**Comment by anthraxx** [comment]
this single import seems to work for my tested cases (oryol and some downstream porjects)

**Comment by floooh** [comment]
Ok, I'm currently running your branch locally on my Mac (with python2 though), if nothing pops up I could merge it after you say it's ready :)

**Comment by anthraxx** [comment]
I guess it's ready, still works on our machines :yum: 
If something pops up i will add a new pull request to fix it :sweat_smile:

**Comment by floooh** [comment]
ok let's see what happens ;)

**Pull request merged**
