### PR TITLE
Fixed incorrect log colors + Improvements to generation time for VSCode on Windows

### PR DESCRIPTION
**Pull request by fLindahl**
Log colors has always been wonky for me: GREEN and RED has worked, but no other colors.
I've changed the color codes, and it seems much more reliable now.

I've tested it in powershell, cmd, debian default terminal and afaik, it works fine.

edit: Also tested in both python 2 and 3

### CODE REVIEW

**Comment by fLindahl** [comment]
Added another small fix: When generating for VSCode, the cmake -LA command will regenerate the project files, which is unnecessary. Added the -N switch which executes cmake in view mode, meaning, it doesn't generate any new files.
This improves the generation time drastically.

**Comment by floooh** [comment]
I'll give it a whirl on Mac, one sec...

**Comment by floooh** [comment]
Btw, doing PRs into a separate branch works better :) (e.g. I already have an old branch named fLindahl-master on my machine, which is probably there from looking at another PR from you that was also created from the master branch).

**Comment by floooh** [comment]
Ok, looking good and merged. Thanks!

**Pull request merged**
