### PR TITLE
launch task permutations for build and pause

### PR DESCRIPTION
**Pull request by rbxnk**
Generally I want my default quick action to be build and launch for quick iteration. I'd been tweaking the generated launch config, but it was getting annoying doing that every regen. This change will add 3 new launch tasks for each permutation of pre launch build and pause at entry.

### CODE REVIEW

**Comment by floooh** [comment]
Hi, sorry for the delay, I'm currently on vacation. I'll try to give the PR a look start of next week!

**Comment by floooh** [comment]
Ok, I just started testing this, and I'm a little bit concerned about the explosion in number of build targets, for instance this is what it looks like now in my emulator-test project:

screen shot 2018-11-22 at 8 29 42 pm

Any ideas how we could trim that down? Maybe one of:

- could just change the behaviour to "build and stop at entry" (worth testing I think)
- add a ```./fips set vscode_debug xxx``` setting, one could then set a preference per project which would be stored in the .fips-settings.yml file (which is usually not under version control)

Thoughts?

**Comment by floooh** [comment]
...hmm on the other hand... if I start debugging with Ctrl+P, "debug ..." it looks much more manageable:

screen shot 2018-11-22 at 8 36 21 pm

...and it will remember the last selection next time when I start debugging with just F5...

I'll use the PR for 2 or 3 days to make up my mind first :)

**Comment by rbxnk** [comment]
The project pref is an interesting idea...

My initial thought to solve this was to add some new cmake functions specific to vscode, but that felt a bit silly since most other IDEs don't integrate launch configuration into the project, or if they do its a user config already.

But making it a fips workspace config keeps your cmake files clean, seems like a good option. Glad to hear that in actual use the long list isn't too bad, its not something that had crossed my mind since the projects I have only have a couple of targets. But even still, this solution isn't exactly future proof/scalable if there are other launch options folks might want.

From your first comment, what if we did both those bullet points, but instead of a "vscode_debug" option its a "vscode_launch" setting, that just directly adds/overrides a field in the launch config when its built? It might have to be its own top level fips command since we'd need to allow defining an arbitrary amount.

Anyway, let me know your thoughts after the test drive, cheers!

**Comment by floooh** [comment]
Alright, I've been using it over the weekend and it works well :)

I'll merge it as is, maybe I'll do a few tweaks later (for instance VSCode recently added support to clear the terminal panel before a new build starts, that's been bothering me for a while...).

Thanks for the PR!

**Pull request merged**
