### PR TITLE
Important bug fix

### PR DESCRIPTION
**Pull request by pixelherodev**
Without this change, I get problems such as this one:
```
[100%] Linking CXX shared library ../../../../../fips-deploy/Oryolized/emsc-make-debug/simple_shell.js
WARNING:root:output suffix .js requested, but wasm side modules are just wasm files; emitting only a .wasm, no .js
```

### CODE REVIEW

**Comment by pixelherodev** [comment]
This fixes a problem with the `emsc-*-debug` configurations when building side modules.

**Comment by floooh** [comment]
Alright, looks like this was an oversight. Thanks!

**Comment by floooh** [comment]
Ah, there's a small bug in there, I'm going to fix this in master. This line is discarding the previous EMSCRIPTEN_LINKER_FLAGS, because it uses still uses EMSCRIPTEN_LINKER_FLAGS_RELEASE as base:

```
set(EMSC_LINKER_FLAGS "${EMSC_LINKER_FLAGS_RELEASE} ...
```

It should be 
```
set(EMSC_LINKER_FLAGS "${EMSC_LINKER_FLAGS} ...
```

**Comment by floooh** [comment]
See: 055b454fa0f55468d3342d6ffbba6e798267ce59

**Comment by pixelherodev** [comment]
Oops yeah sorry - I'd noticed that, but I forgot to push the fix :P

**Pull request merged**
