### PR TITLE
added fips-lua to registry

### PR DESCRIPTION
**Pull request by mgerhardy**

### CODE REVIEW

**Comment by floooh** [comment]
hmm interesting... thanks! :)

**Comment by mgerhardy** [comment]
only tested on linux - feedback welcome

Also the lua commandline interface and the compiler are not included - only liblua

**Comment by mgerhardy** [comment]
now luac is also compiled - working on the commandline interface now.

**Comment by mgerhardy** [comment]
now "everything" (tm) is supported. You get lua, luac and liblua52

have fun. Feedback for mac and windows would still be welcome.

**Pull request merged**
