### PR TITLE
added fips-noisepp to registry

### PR DESCRIPTION
**Pull request by mgerhardy**

### CODE REVIEW

**Comment by floooh** [comment]
What are you using all those noise-libs for? :D

**Comment by mgerhardy** [comment]
trying to build a voxel engine

**Comment by floooh** [comment]
using this https://github.com/nothings/stb/blob/master/stb_voxel_render.h ? if yes let me know how it works :)

**Comment by mgerhardy** [comment]
Nope, currently PolyVox - but I will try that one, too

**Pull request merged**
