### PR TITLE
Remove assumption that current project lies in the same dir as fips.

### PR DESCRIPTION
**Pull request by megaton**
Specifically for fips-configs, fips-toolchains, and fips-verbs logic.

### CODE REVIEW

**Comment by floooh** [comment]
Looks suspiciously simple ;) I'll give it a try in a local branch first. Do you think that all the remaining util.get_project_dir() calls should be replaced too? 

Could you write a few lines here why you had to do this change (how does you project directory structure look like). We only had this discussion over twitter, but it would be good to have the motivation behind the change recorded here.

**Comment by floooh** [comment]
Alright, I tested with my projects, and everything looks alright :)

Thanks for the PR!

**Comment by megaton** [comment]
I have tried to keep it simple, because that is the thing I like about fips -- simplicity :)
The patch was intended to refactor fips behaviour in the following scenario:

Given project with structure like this:
- core: fips-based project
- fips: fips workspace
  - fips
  - oryol
  - ...
- other components
- ...

We need to tell fips that it should be fetched in custom location (here ../fips/fips relatively to core project istead of usual ../fips). Thus fips workspace will not contain "core" project.
That is already possible if you change "fips" file in the "core" project. This is that you more or less allowed to do since this part of fips is in your project repo anyway.

The problem is that after this modification some features of fips (e.g. custom fips-configs and fips-verbs defined in project) was not working correctly.

I hope that this patch has consistently solved this little problem =)

**Comment by megaton** [comment]
> Do you think that all the remaining util.get_project_dir() calls should be replaced too?

Only if you move from flat workspace concept completely one day :) But honestly I do not see much motivation for going that far.

**Pull request merged**
