### PR TITLE
added fips-assimp to registry

### PR DESCRIPTION
**Pull request by mgerhardy**

### CODE REVIEW

**Comment by floooh** [comment]
Seems to require boost :/ Do you have experience with assimp? Happy with it?

**Comment by mgerhardy** [comment]
oh.. there is a workaround for not needing boost - I will try to remove that dependency.

I've just started to use it in my project. It recently got fbx support (not sure how stable that is already) and has some nice commandline tools to do model build chain stuff integration.

**Comment by mgerhardy** [comment]
[quote]
If you want Assimp to use multi-threading for faster performance you could compile Assimp with Boost. You can find the full installation instructions at their [installation page](http://assimp.sourceforge.net/lib_html/install.html)
[/quote]

Is there maybe something like FIPS_BOOSTISFINEFORME ? ;) Even though I (and it looks like you, too) would prevent the boost usage, others might want to use it for the lib because they already use it in their project anyway.

**Comment by mgerhardy** [comment]
https://github.com/assimp/assimp/issues/409

**Comment by floooh** [comment]
If you want to make the boost usage optional, you could add a cmake option to the CMakeLists.txt file, and set the default to OFF, this can then be tweaked in importing projects via 'fips config', or by using a custom build config. Have a look at fips-vld for an example: https://github.com/floooh/fips-vld/blob/master/CMakeLists.txt#L6

**Comment by fungos** [comment]
I've done this too, but have tested only on linux. Here my version, In my case I've opted for disabling BOOST par default because we haven't a fipsified boost. 0.o

https://github.com/fungos/fips-assimp/

**Comment by mgerhardy** [comment]
Yours is looking a lot better - I will delete mine and we should add yours.

**Comment by mgerhardy** [comment]
Created a new pull request #75

**Comment by mgerhardy** [comment]
Btw. I had some time to look into it and create a basic example to load some of our bigger meshes. I like what I've seen so far. Most importantly for me was the fact that you are able to override the IO handling to whatever you like. So async IO and stuff like that works with it.

**Comment by floooh** [comment]
Sounds good, did you try the FBX loader? I think I'll also go with assimp in the future, from what I've seen from browsing the code it all makes sense :)

**Comment by mgerhardy** [comment]
I tested obj, fbx, dae and some other of the delivered samples - but the samples are all very simple models. Obj, fbx and dae were not that simple and our owns. So I can say (up to now) that I'm pleased with the results.

**Pull request merged**
