### PR TITLE
Fix the issue of inability to start on Android 14

### PR DESCRIPTION
**Pull request by Comanx**
Fix the issue where setting android:exported="true" is required to start an Activity on Android 14

### CODE REVIEW

**Comment by floooh** [comment]
Thanks! But hmm, reading the documentation here: https://developer.android.com/privacy-and-security/risks/android-exported

...should it rather be `android:exported="false"`?

I'm still on Android 13 on my phone. Will check if there's an update to Android 14 available and tinker around with that fix before merging. Might be a few days.

**Comment by Comanx** [comment]
https://developer.android.com/about/versions/12/behavior-changes-12#exported
"If the app component includes the [LAUNCHER](https://developer.android.com/reference/android/content/Intent#CATEGORY_LAUNCHER) category, set android:exported to true. In most other cases, set android:exported to false."

**Comment by floooh** [comment]
Giving this a quick test now (on an Android 13 phone though, so just checking if it also works on 13).

**Comment by floooh** [comment]
Blargh, somehow my Android phone is no longer detected when I connect it to my Mac. Probably a latest-macOs-thing. I try to investigate.

**Comment by Comanx** [comment]
You can change ANDROID_PLATFORM: android-28 to android-31, it should not start on Android 13

**Comment by floooh** [comment]
Hmm ok, what is the behaviour on Android 14 when using `ANDROID_PLATFORM: android-28` without the `export` manifest item?

E.g. is `export` actually needed for `platform-31` apps, regardless of the Android OS version?

**Comment by Comanx** [comment]
because "If your app targets Android 12 or higher and contains [activities](https://developer.android.com/guide/components/activities/intro-activities), [services](https://developer.android.com/guide/components/services), or [broadcast receivers](https://developer.android.com/guide/components/broadcasts) that use [intent filters](https://developer.android.com/guide/components/intents-filters#Receiving), you must explicitly declare the [android:exported](https://developer.android.com/guide/topics/manifest/activity-element#exported) attribute for these app components."
https://developer.android.com/about/versions/12/behavior-changes-12#exported

**Comment by floooh** [comment]
...I'm actually able to test now... had to update the Android platform-tools and reboot my Mac (not just 'adb kill-server')

**Comment by floooh** [comment]
Ok, fips should eventually update its default platform in the build configs, but since that can also be configured by the user it's not so high priority IMHO.

Thanks for all the info btw :)

**Comment by floooh** [comment]
PS: as you can see I have merged the your PR without updating the default platform, but if you feel like it, feel free to provide a PR for fips to update to platform-33.

Note that this doesn't only require updating the build config files, but also the installed platform package here:

https://github.com/floooh/fips/blob/3064811b1d02c3a1b4f01a35e77d879be27941cc/mod/android.py#L120

I currently don't have all that much time to look into Android specific things.

**Pull request merged**
