### PR TITLE
open eclipse support

### PR DESCRIPTION
**Pull request by mgerhardy**

### CODE REVIEW

**Comment by floooh** [comment]
I'll try to test this PR first on Windows and OSX (outside Eclipse) in the evening first.

**Comment by floooh** [comment]
Ok looking good. Why is it calling the eclipse command twice though?

**Comment by mgerhardy** [comment]
once it has to import the project - with a headless application - then start the ide. I couldn't find a better way.

**Comment by floooh** [comment]
I see, I just installed a new Ubuntu Mate VM, will give it a try.

**Comment by mgerhardy** [comment]
bildschirmfoto von 2016-03-01 21-40-22

fyi: find an eclipse screenshot attached

**Comment by floooh** [comment]
Yep, just tried it too, first start with the import is slow, but after that it's fast. The hierarchy in the project explorer is quite messy, but I guess that's cmake's fault, not much we can do about it.

**Pull request merged**
